### ISSUE TITLE
How to setup email config

### ISSUE THREAD

**Issue by jbold** [widdix/mastodon-on-aws#12]
Where/how to set up SES + mastodon smtp config?

**Comment by schuettc** [comment]
It just worked for me?  Keep in mind that SES be deployed in sandbox mode.  To get out of that, you'll need to submit a request.  In the meantime, you can use it in sandbox mode, but you'll need to verify the email address you're going to send to.  That can be done in the SES console.  But everything else about SES setup worked out of the box for me.  The confirmation email just didn't come through because the email I was sending to hadn't been verified yet and account was still in sandbox.

**Comment by andreaswittig** [comment]
@jbold @schuettc I'm amazed that your are helping each other out. Have seldomly seen this with our other open-source projects. Keep going! The Mastodon community is rocking it!

**Comment by jbold** [comment]
@schuettc got it 👍 
![image](https://user-images.githubusercontent.com/374123/203247276-eb1e63a9-9fd7-4f5e-9c22-213b589ec004.png)

**Comment by andreaswittig** [comment]
Thanks for bringing this up. I've extended our documentation.
